name: Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Mantenha a versão do Node.js atualizada

    - name: Install dependencies
      run: npm install

    - name: Adjust ESLint permissions
      run: chmod +x ./node_modules/.bin/eslint

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Upload ESLint report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: eslint-report
        path: eslint-report.html
